name: astroo_store_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.6.0

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8

  # Core Firebase Package
  firebase_core: ^3.9.0 # Required to initialize Firebase services in your Flutter app.

  # State Management
  flutter_bloc: ^8.1.6 # State management library using the BLoC (Business Logic Component) pattern.

  # Code Generation and Data Classes
  freezed: ^2.5.7 # A code generator for creating immutable classes and union types in Dart.
  freezed_annotation: ^2.4.4 # Annotations used by the `freezed` package for code generation.
  json_annotation: ^4.9.0 # Annotations used for JSON serialization and deserialization.

  # Networking
  dio: ^5.7.0 # A powerful HTTP client for making network requests in Flutter.
  retrofit: ^4.4.0 # A type-safe HTTP client generator for Dart using annotations.
  pretty_dio_logger: ^1.4.0 # Provides detailed logs for Dio requests, helpful during development and debugging.

  # Local Storage
  shared_preferences: ^2.3.5 # Allows storing small amounts of persistent data locally on the user's device.
  flutter_secure_storage: ^9.2.4 # Provides API to store data in secure storage.

  # UI Design and Animations
  flutter_screenutil: ^5.9.3 # Enables responsive and adaptive UI design for various screen sizes and resolutions.
  animate_do: ^3.3.4 # A package that provides pre-built, customizable animations for Flutter widgets.
  flutter_zoom_drawer: ^3.2.0 #custom implementation of the Side Menu (Drawer)

  # App Configuration
  flutter_launcher_icons: ^0.14.2 # Generates launcher icons for your Flutter app.
  flutter_native_splash: ^2.4.4 # Adds a native splash screen to enhance the user experience during app startup.

  # Logging
  logger: ^2.4.0 # A flexible logging utility for better debug information during development.
  get_it: ^8.0.3
  fluttertoast: ^8.2.10
  shimmer: ^3.0.0
  cached_network_image: ^3.4.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0
  # to generate code use the below command
  # dart run build_runner build --delete-conflicting-outputs
  build_runner: ^2.4.14
  retrofit_generator: ^9.0.0 # for Dart 3.3 use ^9.0.0
  json_serializable: ^6.9.2
 

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/app_icon/
    - assets/images/splash_screen_icon/
    - assets/svg/
    - assets/images/admin/
    - assets/images/common/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/cairo/Cairo-Regular.ttf
        - asset: assets/fonts/cairo/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/cairo/Cairo-Bold.ttf
          weight: 700
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins/Poppins-Regular.ttf
        - asset: assets/fonts/poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/poppins/Poppins-Bold.ttf
          weight: 700
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
flutter_intl:
  enabled: true

flutter_assets:
  assets_path: assets/svg/
  output_path: lib/core/styles/images/
  filename: app_images.dart
  field_prefix: 